
const TVT={
  progressKey(id){return `my-personal-tv-tracker-progress-${id}-v1`;},
  CACHE_KEY:"my-personal-tv-tracker-show-cache-v1",
  SHARED_SHOWS:[
    {query:"The Leftovers",display:"The Leftovers"},
    {query:"The Bear",display:"The Bear"},
    {query:"Riverdale",display:"Riverdale"},
    {query:"Supernatural",display:"Supernatural"},
    {query:"Squid Game",display:"Squid Game"},
    {query:"Silo",display:"Silo"},
    {query:"Hannibal",display:"Hannibal"},
    {query:"Fargo",display:"Fargo"},
    {query:"For All Mankind",display:"For All Mankind"},
    {query:"The Umbrella Academy",display:"The Umbrella Academy"},
    {query:"Peaky Blinders",display:"Peaky Blinders"},
    {query:"Yellowjackets",display:"Yellowjackets"},
    {query:"The X-Files",display:"The X-Files"},
    {query:"Archer",display:"Archer"},
    {query:"Murderbot",display:"Murderbot"},
    {query:"Andor",display:"Andor"},
    {query:"You",display:"You"},
    {query:"Alice in Borderland",display:"Alice in Borderland"},
    {query:"Abbott Elementary",display:"Abbott Elementary"},
    {query:"Doctor Who",display:"Doctor Who",qualifier:"2005"},
    {query:"Sex Education",display:"Sex Education"},
    {query:"Future Man",display:"Future Man"},
    {query:"American Horror Story",display:"American Horror Story"},
    {query:"Game of Thrones",display:"Game of Thrones"},
    {query:"Party Down",display:"Party Down"},
    {query:"The Simpsons",display:"The Simpsons",startSeason:37},
    {query:"Bob's Burgers",display:"Bob's Burgers",startSeason:16},
    {query:"One Piece",display:"One Piece",qualifier:"Netflix"},
    {query:"Malcolm in the Middle",display:"Malcolm in the Middle"},
    {query:"Ted Lasso",display:"Ted Lasso"},
    {query:"Class of '07",display:"Class of '07"},
    {query:"The Movies That Made Us",display:"The Movies That Made Us"},
    {query:"Dark Side of the Ring",display:"Dark Side of the Ring"}
  ],
  getProgress(id){return JSON.parse(localStorage.getItem(this.progressKey(id))||"{}");},
  saveProgress(id,p){localStorage.setItem(this.progressKey(id),JSON.stringify(p));},
  isAired(ep){if(!ep.airdate)return true;const t=new Date();t.setHours(23,59,59,999);return new Date(ep.airdate+"T00:00:00")<=t;},
  formatMinutes(m){const h=Math.floor(m/60),r=m%60;return h?`${h}h ${r}m`:`${r}m`;},
  configForShow(show){const n=(show?.name||"").toLowerCase();return this.SHARED_SHOWS.find(c=>c.display.toLowerCase()===n||c.query.toLowerCase()===n)||null;},
  filterTrackedEpisodes(eps,c){const s=c?.startSeason||1;return eps.filter(e=>e.season&&e.number&&e.season>=s);},
  getShowCache(){try{return JSON.parse(localStorage.getItem(this.CACHE_KEY)||"{}")}catch{return {}}},
  getCachedShow(q){return this.getShowCache()[q]||null;},
  setCachedShow(q,data){const c=this.getShowCache();c[q]={...data,cachedAt:Date.now()};localStorage.setItem(this.CACHE_KEY,JSON.stringify(c));}
};
